### ISSUE TITLE
Only black screen now

### ISSUE THREAD

**Issue by ensonic** [dzikoysk/Pandomium#13]
I am now just getting a black window on linux, I am not sure where the messages come from, they are not in the pandomium sources. Any idea?
```
[17:18:15.903][AWT-EventQueue-1/INFO ] Initialize on Thread[AWT-EventQueue-1,6,main] with library path /home/ensonic/projects/lego/gsoc/pandomium-example/native
LaunchProcess: failed to execvp:
/home/ensonic/projects/lego/gsoc/pandomium-example/native/jcef_helper
LaunchProcess: failed to execvp:
/home/ensonic/projects/lego/gsoc/pandomium-example/native/jcef_helper
LaunchProcess: failed to execvp:
/home/ensonic/projects/lego/gsoc/pandomium-example/native/jcef_helper
LaunchProcess: failed to execvp:
/home/ensonic/projects/lego/gsoc/pandomium-example/native/jcef_helper
LaunchProcess: failed to execvp:
/home/ensonic/projects/lego/gsoc/pandomium-example/native/jcef_helper
LaunchProcess: failed to execvp:
/home/ensonic/projects/lego/gsoc/pandomium-example/native/jcef_helper
LaunchProcess: failed to execvp:
/home/ensonic/projects/lego/gsoc/pandomium-example/native/jcef_helper
[0609/171816.867395:ERROR:browser_gpu_channel_host_factory.cc(103)] Failed to launch GPU process.
```

**Comment by ensonic** [comment]
Did you made a change to write a log file?

When I strace the invocation, I get:
```
133708 execve("/home/ensonic/projects/lego/gsoc/pandomium-example/native/jcef_helper", ["/home/ensonic/projects/lego/gsoc/pandomium-example/native/jcef_helper", "--type=gpu-process", "--no-sandbox", "--lang=en-US", "--locales-dir-path=/home/ensonic/projects/lego/gsoc/pandomium-example/native/locales", "--log-file=/usr/lib/jvm/java-8-openjdk-amd64/jre/bin/debug.log", "--resources-dir-path=/home/ensonic/projects/lego/gsoc/pandomium-example/native", "--use-gl=swiftshader-webgl", "--supports-dual-gpus=false", "--gpu-driver-bug-workarounds=1,7,16,24,63,76", "--disable-gl-extensions=GL_KHR_blend_equation_advanced GL_KHR_blend_equation_advanced_coherent", "--disable-webrtc-hw-encoding", "--gpu-vendor-id=0x8086", "--gpu-device-id=0x0166", "--gpu-driver-vendor=Google Inc.", "--gpu-driver-version=3.3.0.2", "--gpu-driver-date=2017/04/07", "--lang=en-US", "--locales-dir-path=/home/ensonic/projects/lego/gsoc/pandomium-example/native/locales", "--log-file=/usr/lib/jvm/java-8-openjdk-amd64/jre/bin/debug.log", "--resources-dir-path=/home/ensonic/projects/lego/gsoc/pandomium-example/native", "--service-request-channel-token=E0D239198F3EA0AC690C3746E2F581DA"], 0x7f3f0437a940 /* 71 vars */) = -1 EACCES (Permission denied)

```
Main issue seems to be "--log-file=/usr/lib/jvm/java-8-openjdk-amd64/jre/bin/debug.log" and thats hard to workaround. This is still the issues, that chrome sees to switch the cwd to the one from java :/ (see problems in https://github.com/dzikoysk/Pandomium/issues/11#issuecomment-390195132)

It seems that the setting can be changed in:
https://github.com/dzikoysk/Pandomium/blob/master/pandomium/src/main/java/org/cef/CefSettings.java#L71
but I am not sure how to change those. Do you have any ideas?

**Comment by dzikoysk** [comment]
Original source:
  * [CefSettings:144](https://bitbucket.org/chromiumembedded/java-cef/src/f05f91aa59ef9d64f69dfbe7bfd66385fc1189c6/java/org/cef/CefSettings.java?at=master&fileviewer=file-view-default#CefSettings.java-144)

CefSettings usage:
https://github.com/dzikoysk/Pandomium/blob/5f294c24812bb44f50e54d2b9bb5ad4321e2fc31/pandomium/src/main/java/org/panda_lang/pandomium/wrapper/PandomiumThread.java#L35

Is it still not working if you launch application with `sudo`?

**Comment by ensonic** [comment]
it will probably work if I run with sudo, I'll later just termporarily change ownership of that directory to test.

**Comment by ensonic** [comment]
I think there are more problems, will start asking on some cef related forum. I have temporarily chowned myself the jre dir (would be nice to find a fix for this still) and run it. strace reports a bunch of
```
SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_ACCERR
```
Also sudo does not help.

**Comment by ensonic** [comment]
Args. When you download some of the file, this one was not executable. I'll check the code where it needs to be made executable.

   chmod a+x /home/ensonic/projects/lego/gsoc/pandomium-example/native/jcef_helper

**Comment by ensonic** [comment]
The helper path is resolved here:
https://github.com/dzikoysk/Pandomium/blob/master/pandomium/src/main/java/org/cef/CefApp.java#L356
but that does not look like the best place to make the helper executable. What about this
https://github.com/dzikoysk/Pandomium/blob/master/pandomium/src/main/java/org/panda_lang/pandomium/loader/PandomiumNativeLoader.java#L71
I could also add a branch for MacOS. I'd use java.io.File.setExecutable(). If you agree I'll send a PR.

**Comment by dzikoysk** [comment]
Feel free to contribute. I don't have macOS, so I'm not even able to build natives for this system.
