### ISSUE TITLE
Is it possible to use this into non-maven project?

### ISSUE THREAD

**Issue by gumuruhsspj** [dzikoysk/Pandomium#134]
I recently just download the **jcef-win64-fat.jar** because of my windows is using 64bit. But, my question is once i download and deployed into my non-maven project, the code didn't resolved for its imports statements:

```
 Pandomium pandomium = Pandomium.buildDefault();
        PandomiumClient client = pandomium.createClient();
        CefBrowser browser = client.loadURL("http://google.com")
```

Any clues for implementing these pandomium jcef into a non-maven java project?

**Comment by dzikoysk** [comment]
I think it's better to use this project these days:

* https://github.com/jcefmaven/jcefmaven

But yes, you can use both, Pandomium or jcefmaven without using Maven. You have to download all dependencies on your own & bundle it with the app.
