### ISSUE TITLE
Some files are loaded from the jre-bin dir

### ISSUE THREAD

**Issue by ensonic** [dzikoysk/Pandomium#16]
Copied from https://github.com/dzikoysk/Pandomium/issues/11#issuecomment-390195132

When stracing a program using Pandomium I get:
```
32719 open("/home/ensonic/projects/pandomium-example/native/liblinuxenv.so", O_RDONLY) = 20
32719 open("/home/ensonic/projects/pandomium-example/native/liblinuxenv.so", O_RDONLY|O_CLOEXEC) = 20
32719 open("/usr/lib/jvm/java-8-openjdk-amd64/jre/bin", O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = 20
32719 symlink("/home/ensonic/projects/pandomium-example/native/icudtl.dat", "/usr/lib/jvm/java-8-openjdk-amd64/jre/bin/icudtl.dat") = -1 EACCES (Permission denied)
```
and that of course cannot work. What is this trying to achieve? 

If I manually copy (3 files), it starts. 
```
sudo cp native/icudtl.dat /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/
sudo cp native/natives_blob.bin /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/
sudo cp native/snapshot_blob.bin /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/
```
Seems to be similar issue like
https://github.com/cztomczak/cefpython/issues/231
can we apply the same fix?

Here is some special casing does for linux:
https://github.com/dzikoysk/Pandomium/blob/HEAD/pandomium/src/main/java/org/panda_lang/pandomium/loader/PandomiumLoaderWorker.java#L43

**Comment by dzikoysk** [comment]
Could you try to add `native` directory to your `PATH`? (Also remove these files from `/usr/lib/jvm/java-8-openjdk-amd64/jre/bin/`)

**Comment by ensonic** [comment]
Actually it works now. Some update in between seems to have fixed it. Thanks a lot!
