### ISSUE TITLE
Building documentation

### ISSUE THREAD

**Issue by ensonic** [dzikoysk/Pandomium#17]
It would be nice to understand where the cef binaries are downloaded from and how they are built. This could help people to e.g. provide additional builds (macos or e.g. raspberry pi). A little section in the README would be great! Thanks.

FYI; we (https://github.com/OpenRoberta/robertalab) have a GSoC (google summer of code) student working on turning the openrobertalab webapp into a desktop app that one can carry arround and use locally.

**Comment by dzikoysk** [comment]
`Windows x64` - https://github.com/dzikoysk/Pandomium/wiki/Windows-x64-Build

**Comment by dzikoysk** [comment]
`Linux x64` - https://github.com/dzikoysk/Pandomium/wiki/Linux-x64-Build

**Comment by dzikoysk** [comment]
macOS - https://github.com/dzikoysk/Pandomium/wiki/macOS-Build
