### ISSUE TITLE
Lower version GLIBC support

### ISSUE THREAD

**Issue by Peng-YM** [dzikoysk/Pandomium#21]
I want to use Pandomium in a relatively old machine(Centos 6.7) which only have glibc.12(upgrade glibc in customers' host is really painful), however Pandomium67.0 requires glibc2.14.  Is there any solution to run Pandomium in a lower version of glibc? Thanks in advance.

**Comment by dzikoysk** [comment]
Unfortunately, no. It is a libcef.so dependency (cef project) 😩

**Comment by dzikoysk** [comment]
You can try to use Pandomium 1.0.6, I don't know which version of glibc it uses, but maybe a little older.
