### ISSUE TITLE
Can't load AMD 64-bit .dll on a IA 32-bit platform

### ISSUE THREAD

**Issue by rishabhdeepsingh** [dzikoysk/Pandomium#27]
I am trying to Integrate the pandomium in a Project and when i try to run it on my Windows-64 Machine i am getting

`Pandomium - Launching Pandomium 1.0.7`

`Pandomium - Progress: 0%`

`Pandomium - Progress: 100%`

`Exception in thread "PandomiumThread" java.lang.UnsatisfiedLinkError: path\to\native\chrome_elf.dll: Can't load AMD 64-bit .dll on a IA 32-bit platform`

**Comment by Peng-YM** [comment]
This should be JDK error, please look at your output of the command `java -version`, you may used 32-bit java version

**Comment by rishabhdeepsingh** [comment]
Thanks for Helping out.
Resolved.
