### ISSUE TITLE
Error trying to download maven

### ISSUE THREAD

**Issue by eduardobonfa** [dzikoysk/Pandomium#28]
I created a new maven project and added dependency and repository like this: 

<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.mycompany</groupId>
    <artifactId>pandomium-test</artifactId>
    <version>1.0</version>
    <packaging>jar</packaging>
    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.compiler.source>1.8</maven.compiler.source>
        <maven.compiler.target>1.8</maven.compiler.target>
    </properties>
    
    <repositories>
        <repository>
            <id>panda-repository</id>
            <url>https://repo.panda-lang.org/</url>
        </repository>
    </repositories>
    
    <dependencies>
        <dependency>
            <groupId>org.panda-lang</groupId>
            <artifactId>pandomium</artifactId>
            <version>67.0.2</version>
        </dependency>
    </dependencies>
</project>

And I got this error 
Failed to execute goal on project pandomium-test: Could not resolve dependencies for project com.mycompany:pandomium-test:jar:1.0: Failed to collect dependencies for [org.panda-lang:pandomium:jar:67.0.2 (compile)]: Failed to read artifact descriptor for org.panda-lang:pandomium:jar:67.0.2: Failure to find org.panda-lang:pandomium-parent:pom:67.0.2 in https://repo.panda-lang.org/ was cached in the local repository, resolution will not be reattempted until the update interval of panda-repository has elapsed or updates are forced -> [Help 1]

Is anything I'm doing wrong?

**Comment by rishabhdeepsingh** [comment]
Try using 1.0.7 Pandomium Version.

**Comment by eduardobonfa** [comment]
It worked, thanks.
The PandomiumTest.java is not working as well

**Comment by eduardobonfa** [comment]
java.lang.IllegalStateException: Couldn't create parent directory for /home/eduardobonfa/NetBeansProjects/pandomium-test/native/locales/te.pak.

**Comment by dzikoysk** [comment]
`67.0.2` is available: https://repo.panda-lang.org/org/panda-lang/pandomium/67.0.2/pandomium-67.0.2.jar

Remove `org/panda-lang` directory from your local repository (`~/.m2/` by default).
