### ISSUE TITLE
Add Proxy Support

### ISSUE THREAD

**Issue by Ceiridge** [dzikoysk/Pandomium#32]
Good project!
I think proxy support would be very useful, although I'm not sure if it can be added than easily, because Chrome doesn't have any built-in proxy settings but instead uses the Windows Internet Options that affect many other applications.

**Comment by dzikoysk** [comment]
Did you try to use cef proxy? https://bitbucket.org/chromiumembedded/cef/wiki/GeneralUsage#markdown-header-proxy-resolution

**Comment by Ceiridge** [comment]
No, I've also already seen that command line feature, but I'm not sure how to do that with Pandomium.

**Comment by Ceiridge** [comment]
Okay, I literally just had to add that to the command line and it worked. Thanks

**Comment by dzikoysk** [comment]
I think I'll add support for command-line parameters in the Pandomium configuration, you should be able to setup a proxy in your code.

**Comment by dzikoysk** [comment]
#33

**Comment by dzikoysk** [comment]
Something like that should work on Pandomium 63.0.4
```
PandomiumSettings settings = PandomiumSettings.getDefaultSettingsBuilder()
                .proxy("localhost", 20)
                .build();
```
