### ISSUE TITLE
mp4 audio video is not playing inside CEF 

### ISSUE THREAD

**Issue by Raj-chandru** [dzikoysk/Pandomium#40]
Inside CEF mp4 audio and video files are not getting played . I have passed the command line arguments as 
settings.getCommandLine().addArgument("--enable-media-stream");
Still its not working , do i need to enable any other setting or the setting which i have passing is not proper , please suggest

**Comment by dzikoysk** [comment]
This is because these formats was not open and require licensing. Some of them are open now, so I could try to use `proprietary_codecs=1` flag in 70.0 build

**Comment by Raj-chandru** [comment]
Thanks for the update , will mark as know issue in my project and will wait till the 70.0 build is released
