### ISSUE TITLE
Mac archive name is incorrect

### ISSUE THREAD

**Issue by ebremer** [dzikoysk/Pandomium#41]
The below line requests "mac64-natives.tar.xz" and the URL shows it differently:
https://pandomium.panda-lang.org/download/natives/67.0/macosx64-natives.tar.xz

https://github.com/dzikoysk/Pandomium/blob/78f9ea3bc6df3739bc4173d64fa7132ea7b864db/pandomium/src/main/java/org/panda_lang/pandomium/settings/PandomiumSettings.java#L53

**Comment by dzikoysk** [comment]
Unfortunately, macOS is still not supported.

`macosx64-natives.tar.xz` file is part of the:
https://github.com/dzikoysk/Pandomium/pull/36
