### ISSUE TITLE
Blank screen displayed for Test Java Source

### ISSUE THREAD

**Issue by kumarkrish85** [dzikoysk/Pandomium#42]
I have downloaded the JAR and Kept in Java class path. For the Test Java source, I got the below console output and in Swing component shows blank screen

ant -f C:\\Users\\589103\\Documents\\NetBeansProjects\\test -Dnb.internal.action.name=run.single -Djavac.includes=test/Test.java -Drun.class=test.Test run-single
init:
Deleting: C:\Users\589103\Documents\NetBeansProjects\test\build\built-jar.properties
deps-jar:
Updating property file: C:\Users\589103\Documents\NetBeansProjects\test\build\built-jar.properties
Compiling 1 source file to C:\Users\589103\Documents\NetBeansProjects\test\build\classes
compile-single:
run-single:
[12:36:48.981][main/INFO ] #
[12:36:48.983][main/INFO ] # Launching Pandomium 67.0.4
[12:36:48.983][main/INFO ] # Chromium Version: 67.0.3396.62
[12:36:48.983][main/INFO ] # CEF Version: 3.3396.1775.g5340bb0
[12:36:48.983][main/INFO ] #
[12:36:48.984][main/INFO ] Progress: 0%
WARNING: An illegal reflective access operation has occurred
[12:36:48.989][main/INFO ] Progress: 100%
WARNING: Illegal reflective access by org.panda_lang.pandomium.util.SystemUtils (file:/C:/Users/589103/Downloads/pandomium-67.0.4.jar) to field java.lang.ClassLoader.sys_paths
WARNING: Please consider reporting this to the maintainers of org.panda_lang.pandomium.util.SystemUtils
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
initialize on Thread[AWT-EventQueue-0,6,main] with library path C:\Users\589103\Documents\NetBeansProjects\test\natives
**[0201/123649.416:ERROR:gpu_process_transport_factory.cc(1027)] Lost UI shared context.**

Please help

**Comment by dzikoysk** [comment]
Use Java 8, jcef doesn't support higher versions
