### ISSUE TITLE
Basic JS bridge

### ISSUE THREAD

**Issue by jaisonpereira** [dzikoysk/Pandomium#43]
Advanced Java <-> JS bridge is one future implementation , but is there one basic way to call java method from js ?
Ex: with  CefMessageRouter i can do that

**Comment by dzikoysk** [comment]
You should be able to use CefMessageRouter as you want. Pandomium is just a little wrapper for now and it allows you to get original jcef objects.

**Comment by jaisonpereira** [comment]
yeah, I followed that step but, unfortunately, I got this error:
"The query has been canceled",

Java Side:


`
	Pandomium pandomium = new Pandomium(PandomiumSettings.getDefaultSettings());
		pandomium.initialize();

		PandomiumClient client = pandomium.createClient();

		CefMessageRouterConfig config = new CefMessageRouterConfig();
		config.jsQueryFunction = "cefQuery";
		config.jsQueryFunction = "cefQueryCancel";

		CefMessageRouter msgRouter = CefMessageRouter.create();
		msgRouter.addHandler(new HandlerMessageRouter(), true);
//		msgRouter.addHandler(new PrinterMessageRouter(client), false);
//		addMessageRouter(msgRouter);
		client.getCefClient().addMessageRouter(msgRouter);

		PandomiumBrowser browser = client.loadURL(LOCALHOST);

		JFrame frame = new JFrame();
		frame.getContentPane().add(browser.toAWTComponent(), BorderLayout.CENTER);

		frame.setDefaultCloseOperation(WindowConstants.DO_NOTHING_ON_CLOSE);
		frame.addWindowListener(new WindowAdapter() {
			@Override
			public void windowClosing(WindowEvent e) {
				frame.dispose();
				System.exit(0);
			}
		});

		frame.setTitle("Pandomium");
		frame.setSize(1720, 840);
		frame.setExtendedState(java.awt.Frame.MAXIMIZED_BOTH);
		frame.setVisible(true);
`

Implementation Handler:
`
public class HandlerMessageRouter extends CefMessageRouterHandlerAdapter {
	public boolean onQuery(CefBrowser browser, long query_id, String request, boolean persistent,
			CefQueryCallback callback) {
		System.out.println("get this");
		System.out.println(query_id);
		System.out.println(request);
		JOptionPane.showMessageDialog(null, "received");
		if (request.indexOf("print") == 0) {
			callback.success("print sucessfull");
			return true;
		}
		return true; // Not handled.
	}

	public void onQueryCanceled(CefBrowser browser, long query_id) {

		System.out.println("cancel");
	}

}
`

Web Side:

`
 var request_id = (<any>window).cefQuery({
      request: 'print',
      persistent: false,
      onSuccess: function (response) {
        alert('print sended');
        console.log(response);
      },
      onFailure: function (error_code, error_message) {
        console.log(error_message);
        console.log(error_code);
        alert('failure print');
      }
    });

`

**Comment by dzikoysk** [comment]
I didn't use the message router, so I'm not sure I can help you. I think you should ask on JCEF issue tracker, because it's their api and they should know what's going on:
* https://bitbucket.org/chromiumembedded/java-cef/issues

**Comment by jaisonpereira** [comment]
Ok thanks, I will see that
