### ISSUE TITLE
Getting/Setting cookies

### ISSUE THREAD

**Issue by Ceiridge** [dzikoysk/Pandomium#44]
Hi,
how can I get and set cookies with Pandomium?
In _CefSharp_, there's the _CookieManager_.
Is it possible in Pandomium?

**Comment by dzikoysk** [comment]
Pandomium is just a wrapper for JCEF, you should check their api for more information. It looks like they provide some tools to do that:

![obraz](https://user-images.githubusercontent.com/4235722/56853374-0f216a80-6927-11e9-997a-843549d80da4.png)
![obraz](https://user-images.githubusercontent.com/4235722/56853407-6a535d00-6927-11e9-94e7-055e5222575a.png)
