### ISSUE TITLE
Internal Logging of Pandomium overwrites handling of my application's LogBack

### ISSUE THREAD

**Issue by JRSofty** [dzikoysk/Pandomium#45]
I use Logback for my application logging, and I've found that when I use Pandomium I'm getting this warning:

    SLF4J: Class path contains multiple SLF4J bindings.
    SLF4J: Found binding in [jar:file:/F:/Development/.m2/org/panda-lang/pandomium/67.0.3/pandomium-67.0.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
    SLF4J: Found binding in [jar:file:/F:/Development/.m2/ch/qos/logback/logback-classic/1.2.3/logback-classic-1.2.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
    SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
    SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]

It seems that instead of making your library require SLF4J you are actually embedding it into the jar like it was an application (along with all the other dependencies). This makes it difficult for people who wish to use Pandomium and configure its logging to match our application.

Would it be too much to ask for a simple jar and not a fat jar?

**Comment by dzikoysk** [comment]
I'm really busy currently, so I'm not able to improve these builds right now - especially that the problem is caused by another library. Consider exclusion of your slf4j implementation for a while, I'll take care of that in the future update.

**Comment by JRSofty** [comment]
That's fine, do you have a problem if I clone your repo make a change and
send you a pull request?

**Comment by dzikoysk** [comment]
No, any contributions are highly appreciated  ❤

**Comment by JRSofty** [comment]
I've checked out the master, but I can't seem to push. Can you give me a branch that I can checkout and push to, then I'll make a pull request for you to review.

**Comment by dzikoysk** [comment]
You should fork this repository and push your changes to that fork, then you should be able to create pull request :)

~ https://guides.github.com/activities/forking/

**Comment by JRSofty** [comment]
Thanks, that's got it working. Not used to working with others in GitHub yet ;)

My fixes have been made in my fork and I've made a pull request. Thanks for the support.

**Comment by dzikoysk** [comment]
Pandomium 67.0.5 released with your changes :)
