### ISSUE TITLE
Render from string and get DOM afterwards

### ISSUE THREAD

**Issue by christian-draeger** [dzikoysk/Pandomium#48]
Is it possible to use Pandomium to render html given by a String?
currently I only see the possiblility to make a HTTP request using pandonium (or CEF).
```
client.loadURL("https://panda-lang.org")
```
Is it somehow possible to to pass HTML from a string? to get it more clear, something like:
```
client.loadRaw("<!DOCTYPE html>
<html lang="en">
    <head></head>
    <body></body>
    <script>
        var dynamicallyAddedElement = document.createElement("div");
        dynamicallyAddedElement.className = "dynamic";
        var textNode = document.createTextNode("I have been dynamically added via Javascript");
        dynamicallyAddedElement.appendChild(textNode);
        document.body.appendChild(dynamicallyAddedElement);

    </script>
</html>")
```

Furthermore i would be intressted in getting the pagesource after the javascript has been executed and would expect to get this:
```
<html lang="en">
    <head></head>
    <body>
        <div class="dynamic">I have been dynamically added via Javascript</div>
    </body>
    <script>
        var dynamicallyAddedElement = document.createElement("div");
        dynamicallyAddedElement.className = "dynamic";
        var textNode = document.createTextNode("I have been dynamically added via Javascript");
        dynamicallyAddedElement.appendChild(textNode);
        document.body.appendChild(dynamicallyAddedElement);

    </script>
</html>
```

is this possible with pandomium in some way or could be supported by any chance in the nearer future?

What I'm trying to archive is to build something that is giving me a pagesource after executing javascript etc. 
Images, styles etc doesn't have to be rendered necessarily. I just want to use it as a rendering engine to write a DOM parser. I don't need to see the visual rendered page, I need to see the generated source code but executed by a modern engine (like chromium). Do you have any tipps if it's realistic to use pandomium in this case or have any approach how to realize it?

**Comment by dzikoysk** [comment]
Pandomium is just a wrapper for https://bitbucket.org/chromiumembedded/java-cef and you should ask them about features like that. I'm just simplifying the building/initialization process.

Anyway, you should be able to use: https://en.wikipedia.org/wiki/Data_URI_scheme
