### ISSUE TITLE
Native lib path

### ISSUE THREAD

**Issue by Fxztam** [dzikoysk/Pandomium#49]
After correct downloding the win64-natives.tar.xz there is a issue with the native lib path:

[13:03:41.579][main/INFO ] Close connections
[13:03:41.581][main/INFO ] Progress: 99%
java.lang.NoSuchFieldException: sys_paths
	at java.lang.Class.getDeclaredField(Class.java:820)
	at org.panda_lang.pandomium.util.SystemUtils.injectLibraryPath(SystemUtils.java:12)

![image](https://user-images.githubusercontent.com/5808032/57295886-cfe3de00-70cb-11e9-8706-8bf0089d3379.png)

Can you log the _libraryPath_ please, could help something..
( I tried on the same point a lot ;-) )

Thanks

**Comment by Fxztam** [comment]
The unpacking is correct : 
![image](https://user-images.githubusercontent.com/5808032/57296325-079f5580-70cd-11e9-87a4-2a6cc4df2631.png)

Great !

**Comment by dzikoysk** [comment]
What's your JVM version? It looks like other implementation than Oracle: https://github.com/MultiMC/MultiMC5/issues/1320

**Comment by Fxztam** [comment]
Yes, you are right - Oj9 :
![image](https://user-images.githubusercontent.com/5808032/57298698-20ab0500-70d3-11e9-89e6-fb14b4d96dc1.png)

**Comment by Fxztam** [comment]
Sorry, full name: **AdaptOpenJDK 8.0.212.3 OpenJ9**

**Comment by dzikoysk** [comment]
Check out the new release:

```xml
<dependency>
    <groupId>org.panda-lang</groupId>
    <artifactId>pandomium</artifactId>
    <version>67.0.6</version>
</dependency>
```

**Comment by Fxztam** [comment]
Works great now:
![image](https://user-images.githubusercontent.com/5808032/57301840-307a1780-70da-11e9-85c3-f87e192906b4.png)

Awesome !
