### ISSUE TITLE
How to show dev tools?

### ISSUE THREAD

**Issue by stefaneidelloth** [dzikoysk/Pandomium#53]
I tried to open dev tools with F12... did not work. 

I seem to be able to get dev tools with

```
var client = pandomium.createClient();
var pandomiumBrowser = client.loadURL("...");
var browser = pandomiumBrowser.getCefBrowser();
var devTools = browser.getDevTools();
```

**But how to show those dev tools?**

I tried

```
JFrame frame = new JFrame();
var content = frame.getContentPane();
 
content.add(pandomiumBrowser.toAWTComponent(), BorderLayout.CENTER);
content.add((Component) devTools, BorderLayout.SOUTH);

but CefBrowser is no component.
```

**Comment by dzikoysk** [comment]
Probably your layout is just not displaying component. Example with new frame: 
![obraz](https://user-images.githubusercontent.com/4235722/58570848-f8797680-8238-11e9-8a5b-82f72387d5c2.png)

~ https://github.com/dzikoysk/Pandomium/blob/master/pandomium/src/test/java/org/panda_lang/pandomium/PandomiumDevTools.java

**Comment by stefaneidelloth** [comment]
Ahh...
I looked for 

toAWTComponent

and oversaw

getUIComponent()

Thanks.
