### ISSUE TITLE
Browser not using full space on 4k Display

### ISSUE THREAD

**Issue by LeonBein** [dzikoysk/Pandomium#54]
When running the [PandomiumTest.java](https://github.com/dzikoysk/Pandomium/blob/master/pandomium/src/test/java/org/panda_lang/pandomium/PandomiumTest.java) using Pandomium 67.0.6 on a 4k display, not all available space is used, as seen in this screenshot:
![grafik](https://user-images.githubusercontent.com/28008098/59096110-6b11e280-891a-11e9-800a-3eef4a726025.png)
Changing the background color of the `browser.toAWTComponent()` shows me, that the component is full sized, but just does not render the full space.
When trying again on another, smaller display, everything works out fine, so I assume its due to the display, but I am not 100% sure.

**Comment by dzikoysk** [comment]
Pandomium is just wrapping JCEF, so you should report this issue here: https://bitbucket.org/chromiumembedded/java-cef/issues :)

I'm also not able to reproduce that so I can't give you any useful solution, especially if it is just a bug 😞

**Comment by LeonBein** [comment]
Just as update: I found the apperently same issue [here](https://bitbucket.org/chromiumembedded/java-cef/issues/75/windows-hidpi-display-renders-incorrectly), but it says it was closed three years ago, so I am not sure if there are any useful information there.
