### ISSUE TITLE
Pandomium not starting, no access.

### ISSUE THREAD

**Issue by KVAC** [dzikoysk/pandomium#58]
My OS:
Linux  5.3.10-arch1-1 #1 SMP PREEMPT Sun, 10 Nov 2019 11:29:38 +0000 x86_64 GNU/Linux

FULL LOG (console):
[main/INFO ] #
[main/INFO ] # Launching Pandomium 67.0.6
[main/INFO ] # Chromium Version: 67.0.3396.62
[main/INFO ] # CEF Version: 3.3396.1775.g5340bb0
[main/INFO ] #
[main/INFO ] Progress: 0%
[main/ERROR] Pandomium requires permission to /usr/lib/jvm/java-8-openjdk/jre/bin directory
[main/ERROR] Pandomium requires permission to /usr/lib/jvm/java-8-openjdk/jre/bin directory
[main/ERROR] Pandomium requires permission to /usr/lib/jvm/java-8-openjdk/jre/bin directory
[main/INFO ] Progress: 100%
initialize on Thread[AWT-EventQueue-1,6,main] with library path /home/..../eclipse-workspace/..../natives
[1112/180915.880187:ERROR:icu_util.cc(133)] Invalid file descriptor to ICU data received.

Process 1327429 (java) of user 1000 dumped core.
Stack trace of thread 1327586:
#0  0x00007fb502510f11 n/a (/home/ougi_oshino/eclipse-workspace/.../natives/libcef.so)
#1  0x00007fb5038068b5 n/a (/home/ougi_oshino/eclipse-workspace/.../natives/libcef.so)
#2  0x00007fb50254627d n/a (/home/ougi_oshino/eclipse-workspace/.../natives/libcef.so)
#3  0x00007fb502545f70 n/a (/home/ougi_oshino/eclipse-workspace/.../natives/libcef.so)
#4  0x00007fb500c10fa0 n/a (/home/ougi_oshino/eclipse-workspace/.../natives/libcef.so)
#5  0x00007fb4fe5a64f4 n/a (/home/ougi_oshino/eclipse-workspace/.../natives/libjcef.so)

-rwxr-xr-x 1 ... ... 131575424 $(Date) /home/..../eclipse-workspace/..../natives/libcef.so

ldd libcef.so (no dependencies found)

strace:
openat(AT_FDCWD, "/usr/lib/jvm/java-8-openjdk/jre/bin/../lib/amd64/jli/libm.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (not found)
openat(AT_FDCWD, "/usr/lib/jvm/java-8-openjdk/jre/bin/../lib/amd64/libm.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (not found)

**Comment by KVAC** [comment]
UDP: Works only after the first run with root privileges (Links are created).
If possible, fix it.

**Comment by dzikoysk** [comment]
JCEF needs to create symlinks on Linux in java directory, so you have to launch application at least once with permission to write in the specified directory:

`
[main/ERROR] Pandomium requires permission to /usr/lib/jvm/java-8-openjdk/jre/bin directory
`

~ due to: https://www.google.com/search?client=firefox-b-d&q=Invalid+file+descriptor+to+ICU+data+received
