### ISSUE TITLE
Issue on build with ubuntu 20.04

### ISSUE THREAD

**Issue by DanishSheraz575** [dzikoysk/pandomium#65]
after the successful build when i run test with:
./run.bat linux64 Release detailed
it shows the following error:
![Screenshot from 2021-03-31 12-48-10](https://user-images.githubusercontent.com/20401194/113109727-b304a680-921f-11eb-910b-e437ff823b72.png)
Need Help !

**Comment by dzikoysk** [comment]
Sorry for late response, I somehow missed notification. `Bat` files are Windows scripts (https://en.wikipedia.org/wiki/Batch_file), so you just need to use `.sh` script.
