### ISSUE TITLE
basic Java <> JavaScript Bridge ?

### ISSUE THREAD

**Issue by gochev** [dzikoysk/pandomium#66]
I know in the todo there is a TODO for advanced bridge.

but is there a basic bridge ? is there any docs or example of it ? 

I tried using the CEF docs

```
CefMessageRouter msgRouter = CefMessageRouter.create();
msgRouter.addHandler(new MessageRouterHandler(), true);
client.getCefClient().addMessageRouter(msgRouter);
```

Then having a handler like this

```
public class MessageRouterHandler extends CefMessageRouterHandlerAdapter {
  public boolean onQuery(CefBrowser browser,
                         long query_id,
                         String request,
                         boolean persistent,
                         CefQueryCallback callback) {
    System.out.println("on Query");
    if (request.indexOf("BindingTest:") == 0) {
      // Reverse the message and return it to the JavaScript caller.
      String msg = request.substring(12);
      callback.success(new StringBuilder(msg).reverse().toString());
      return true;
    }
    // Not handled.
    return false;
  }
}
```

and a file having JS code like this

```
function sendMessage() {
    debugger;
  // Results in a call to the OnQuery method in binding_test.cpp
  window.cefQuery({
    request: 'BindingTest:' + document.getElementById("message").value,
    onSuccess: function(response) {
      document.getElementById('result').value = 'Response: '+response;
    },
    onFailure: function(error_code, error_message) {}
  });
}
</script>
```

the window.cefQuery is called but the Java doesn't recieve anything 

P.S. super project.. I am super hyped !

**Comment by dzikoysk** [comment]
Hi :)

Unfortunately, at this moment Pandomium is on hold as I'm involved in other projects. Remember that it only wraps and automates process of using JCEF, so any issues related to the JCEF you should report here:

* https://bitbucket.org/chromiumembedded/java-cef/issues?status=new&status=open

I don't quite remember how to communicate with the builtin js integration, as far as I remember it was kinda painful. I hope you'll get through it.

**Comment by gochev** [comment]
Hey @dzikoysk  I understand I really hope this project will not be left in the dust because to be able to have maven build where JCEF just works is a god send especially if it supports all major OSes.

About the bridge I will make it ... somehow and we can discuss what we can do about the advanced js bridge since I have to implement something like this on my own anyway 🤣🤣 You can close this one I guess :)

**Comment by gochev** [comment]
I have it working by looking at this example https://github.com/viglucci/app-jcef-example/blob/master/src/main/java/org/cef/browser/CefMessageRouter.java

read the comments ;)
