### ISSUE TITLE
Move to Maven 2 official repository

### ISSUE THREAD

**Issue by gochev** [dzikoysk/pandomium#68]
I do not see a reason why the project is not available in maven2 central  repository.

This would:
1) not require extra repository config
2) relay on the fact that most maven projects are already there so will minimize network issues.
3) easier building from internal systems that doesn't have access to third party websites.

Since the project is mostly for making the JCEF easier to use for maven projects this will make it even easier.

**Comment by dzikoysk** [comment]
This project was dedicated for my personal projects and it's just easier for me to maintain it through my public repository from associated organization. Moving to Maven central, despite of a fact you don't have to declare a new repository, causes problem like a less control over the repository content, where I could put various extra resources like natives etc. It's also less stable, from my internal Maven researches Maven centeral is less stable than my personal repo and it timeouts from time to time.

**Comment by dzikoysk** [comment]
https://github.com/dzikoysk/pandomium/issues/80#issuecomment-997078418
