### ISSUE TITLE
Cleanup repository

### ISSUE THREAD

**Issue by dzikoysk** [dzikoysk/pandomium#73]

**Comment by dzikoysk** [comment]
* Remove https://github.com/dzikoysk/pandomium/tree/master/pandomium-cef/cef as finally we wouldn't change anything in these sources to keep the maintainability. In the future fixes should be provided as git patches.

**Comment by dzikoysk** [comment]
* Remove https://github.com/dzikoysk/pandomium/tree/master/pandomium-macos as it might be misleading that Pandomium supports it. At this moment there is no way we can handle macOS builds I guess 🤔

**Comment by Osiris-Team** [comment]
Guess we can close this too ^^
