### ISSUE TITLE
JUnit tests inside pandomium project not working because java.path gets not set?

### ISSUE THREAD

**Issue by Osiris-Team** [dzikoysk/pandomium#78]
I tried running tests multiple times, but this is the exception I get when I try to init Pandomium: `java.lang.UnsatisfiedLinkError: no chrome_elf in java.library.path`.
I checked the `java.library.path` with `System.getProperty()` and it seems that it's set, but that doesn't make a difference it seems.
Any ideas?

**Comment by dzikoysk** [comment]
Does the path contain valid /native directory that exists in working directory of app instance?

**Comment by Osiris-Team** [comment]
Yep

**Comment by Osiris-Team** [comment]
I just tried it on with the latest release, on another project (with junit) and there everything works fine.
Its just when running tests inside the pandomium project it seems.

**Comment by dzikoysk** [comment]
I think you could try to find the load call of `chrome_elf` in jcef sources and just debug the test to see what's happening in the internals 🤔

**Comment by dzikoysk** [comment]
How it's going? :)

**Comment by Osiris-Team** [comment]
I just gave up and started writing my own new browser from scratch without dependencies on chrome or firefox.

**Comment by dzikoysk** [comment]
Oh, right, so the current sources on master are just broken for now? :/

**Comment by Osiris-Team** [comment]
Idk. When using Pandomium on another project as dependency I can run tests without problems.

**Comment by dzikoysk** [comment]
Tried to launch, but even if it starts properly I get blank white page no matter what I try to load. Kinda strange

**Comment by Osiris-Team** [comment]
Yep just tried it and get the same issue. Did you run it as test or in a build application?

**Comment by dzikoysk** [comment]
Just launched PandomiumTest class through main method in IntelliJ. It looks like the JCEF doesn't fill the AWT component with content 🤔 With verbose logging there is still no any message that could say that something went wrong, I guess it may require extra debugging to find out what's going on.

**Comment by Osiris-Team** [comment]
@dzikoysk found a workaround for our problem haha: https://github.com/Osiris-Team/Headless-Browser

**Comment by dzikoysk** [comment]
Well, it's just headless browser, so it's quite opposite target, because Pandomium is mostly dedicated for GUI apps with visible renderer 🤔

**Comment by Osiris-Team** [comment]
True you can easily bind Pandomium to a java fx, that's not possible with Pupetter I guess, even though it can run with an GUI too.

**Comment by dzikoysk** [comment]
There is like 2/6/12 asset versions, kinda strange tbh 🤔

**Comment by Osiris-Team** [comment]
Just found out the blank screen issue. It was indeed because of the latest jcef version.
I just downgraded to an older jcef version and there is no blank page/window problem anymore.
