### ISSUE TITLE
Digital Certificate

### ISSUE THREAD

**Issue by resplandes** [dzikoysk/pandomium#83]
How can I access a website that requires a digital certificate?

**Comment by FriwiDev** [comment]
What kind of website do you mean? A website using https or a website requiring you to upload a certificate to login?

**Comment by resplandes** [comment]
a site that requires you to upload/select a certificate to login

https://www.nfe.fazenda.gov.br/portal/consultaRecaptcha.aspx?tipoConsulta=resumo&tipoConteudo=7PhJ+gAVw2g=

**Comment by FriwiDev** [comment]
There is a pull request for this on the official jcef repo. For now this feature seems to be unavailable, unless you want to build the pull request yourself: https://bitbucket.org/chromiumembedded/java-cef/pull-requests/47

According to the forums, jcef currently selects the first certificate automatically: https://magpcss.org/ceforum/viewtopic.php?f=17&t=17705

**Comment by dzikoysk** [comment]
As we're not really in position to provide this feature, I'm closing this. Thanks @FriwiDev for details about this case! :)
